### ISSUE TITLE
Dock not loading

### ISSUE THREAD

**Issue by AdryanDs** [xuzhen/dockbarx-lxqt-plugin#1]
On Arch Lxqt i can't add dock to panel. I've installed from aur and later manually from git, either not loading. Any idea why?

**Comment by xuzhen** [comment]
This plugin is based on Qt 5 and is for lxqt-panel 1.4.0. Arch's lxqt-panel is already 2.0.1 and based on Qt 6.
I'll look into the compatibility issue this weekend.

**Comment by AdryanDs** [comment]
Alright, thank you!

**Comment by xuzhen** [comment]
The [version 0.9.1](https://github.com/xuzhen/dockbarx-lxqt-plugin/releases/tag/v0.9.1) should work

**Comment by AdryanDs** [comment]
Thank you again very much! Saturday after update, i checked and i did can load to panel this plugin, but it had strange behaviour in the panel. I can't pin apps to dock and other things. I tried both regular from aur and git version, so for now i abandon lxqt, but maybe i'll return to it soon. Thanks for your effort, i appreciate your work

**Comment by KF-Art** [comment]
Since 0.9.1 was released now it works correctly in LXQt 2.0.0.
So I guess this can be closed as completed?

**Comment by Vistaus** [comment]
It doesn't work for me. When I add it to the panel, it opens a window with the previous window contents visible and the title lxqt-panel-applet.py It only does that and it doesn't add the widget to the panel. So it's still not loading on LXQt 2.0.0 with Qt 6 and Arch Linux.

**Comment by xuzhen** [comment]
@Vistaus Did you tried the newest version 0.9.4? The version 0.9.1 in AUR is a bit outdated. If still doesn't work properly, please post the output after running lxqt-panel in terminal (kill existing one first).

**Comment by Vistaus** [comment]
@xuzhen Thanks. I noticed it was old, so I installed dockbarx-lxqt-plugin-git from AUR instead. Sorry, I should've mentioned that earlier.

I'll try killing the panel posting the output later.

**Comment by Vistaus** [comment]
```
❯ lxqt-panel 
StatusNotifier: registration of service org.kde.StatusNotifierWatcher queued, we can become primary after existing one deregisters
starting
WinIdChange 3000008 handle QWidgetWindow(0x5e68da969b20, name="LXQtPanel panel1Window") QScreen(0x5e68d9cedf50, name="HDMI-A-1")
StatusNotifierProxy, services: QList()
Manager selection claimed
trying to dock window  35651596
adding damage watch for  35651596
could not register SNI: "No such object path '/StatusNotifierWatcher'"
Container window visible, stack below
DockbarX 1.0-beta4
DockbarX init
DockbarX reload
DockbarX 1.0-beta4
DockbarX init
DockbarX reload
DockbarX 1.0-beta4
DockbarX init
DockbarX reload
DockbarX 1.0-beta4
DockbarX init
DockbarX reload
```

**Comment by xuzhen** [comment]
> ```
> DockbarX 1.0-beta4
> DockbarX init
> DockbarX reload
> DockbarX 1.0-beta4
> DockbarX init
> DockbarX reload
> DockbarX 1.0-beta4
> DockbarX init
> DockbarX reload
> DockbarX 1.0-beta4
> DockbarX init
> DockbarX reload
> ```
@Vistaus  It appears that the program /usr/share/dockbarx/lxqt-panel-applet.py keeps crashing and restarting repeatedly.
Please remove the plugin from lxqt-panel or just kill the panel,  then run /usr/share/dockbarx/lxqt-panel-applet.py directly  and post the output.

**Comment by Vistaus** [comment]
@xuzhen I followed your instructions and the dock does appear briefly (outside of the panel, though), but then it crashes and doesn't re-appear. The terminal output is the exact same as the earlier output.

**Comment by xuzhen** [comment]
> @xuzhen I followed your instructions and the dock does appear briefly (outside of the panel, though), but then it crashes and doesn't re-appear. The terminal output is the exact same as the earlier output.

No error information? Strange.
Run this command `python3 -m trace -t /usr/share/dockbarx/lxqt-panel-applet.py >/tmp/a.log` and upload /tmp/a.log. 
It may be several megabytes, compress using 7z or xz would greatly reduce its size.

**Comment by Vistaus** [comment]
Here's the log (compressed) attached.
[a.tar.gz](https://github.com/user-attachments/files/17529871/a.tar.gz)

**Comment by xuzhen** [comment]
﻿@Vistaus The log shows that the process of /usr/share/dockbarx/lxqt-panel-applet.py received a SIGINT signal. ﻿There's no clue in the log about which process sent it.

﻿You can install and run `bpftrace` to monitor which process sent the signal. `sudo /usr/share/bpftrace/tools/killsnoop.bt`
Another choice is `bcc-tools`: `sudo /usr/share/bcc/tools/killsnoop`

**Comment by Vistaus** [comment]
@xuzhen Weirdly enough, bpftrace doesn't show anything that killed it. :/
