### ISSUE TITLE
Plugin icons are too small compared to the rest of icons in the panel

### ISSUE THREAD

**Issue by KF-Art** [xuzhen/dockbarx-lxqt-plugin#2]
After updating to 0.9.3 from 0.9.1 icons are too small compared to other icons in the panel and there's no apparent way to increase their size individually (its size depends on panel's icon size setting, but to get a similar size to before, the rest of icons end up being too big or too separated). This happens with 0.9.2 as well.

![imagen](https://github.com/user-attachments/assets/20fd1e4d-560f-4a54-bb65-fe3057825762)
Panel in 0.9.3

![imagen](https://github.com/user-attachments/assets/8c430fc3-d250-4ae7-b064-f4b04ae1c519)
Panel in 0.9.3 with icon size at 42px (previously it was 24px).

![imagen](https://github.com/user-attachments/assets/ab944a42-0119-4b9a-a831-2d791aa7f7ce)
Panel in 0.9.1 (icon size at 24px)

Is this intended? If not, is there some workaround for this?
Thanks beforehand. Cheers.

**Comment by xuzhen** [comment]
﻿Yes, in version 0.9.3, the actual size of icons displayed may be smaller than what is set in the panel's icon size option depending on which DockbarX theme you are using.

﻿In version 0.9.4, you can set a custom icon size to make the icons larger.
![a](https://github.com/user-attachments/assets/1a7573b7-7e84-4137-9ea0-0e20759eac35)

**Comment by KF-Art** [comment]
Excellent, I've just updated and works like a charm.
Thanks for your great work.
